[project]
name = "mcp-basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "fastapi-mcp>=0.4.0",
    "fastmcp>=2.14.4",
    "feedparser>=6.0.12",
    "uvicorn[standard]>=0.40.0",
]
